# META
site_name: KronoDocs
copyright: © Copyright 2006-2020 Inflectra Corporation, All Rights Reserved | en-US |

repo_name: Inflectra
repo_url: https://www.inflectra.com
site_url: https://kronodoc.inflectra.com/

# EXTENSIONS USED
markdown_extensions:
  - attr_list
  - footnotes
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - toc:
      permalink: true

# THEME INFORMATION
theme:
  features:
    - instant
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en 
  name: material
  palette:
    primary: black
    accent: amber
  font:
    code: IBM Plex Mono
  favicon: images/favicon.ico
  logo: images/logo.svg
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/inflectra
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/inflectra
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/inflectra-corporation
  analytics:
    provider: custom
    property: see the custom.html partial


# NAVIGATION MENU
nav:
  - User Manual:
    - How to use this manual: User-Manual\index.md
    - Functionality Overview: User-Manual\Functionality-Overview.md
    - Home Page: User-Manual\Home-Page.md
    - Knowledge Base: User-Manual\Knowledge-Base.md
    - Forums: User-Manual\Forums.md
    - Help Desk: User-Manual\Help-Desk.md
    - User Profile: User-Manual\User-Profile.md
    - Reports: User-Manual\Reports.md
  - Quick Start Guide: Quick-Start-Guide\index.md
  - Administration Guide: 
    - How to use this guide: Administration-Guide\index.md
    - Installing KronoDesk: Administration-Guide\Installing-KronoDesk.md
    - System Administration: Administration-Guide\System-Administration.md
    - System Settings: Administration-Guide\System-Settings.md
    - Users: Administration-Guide\Users.md
    - Forum Settings: Administration-Guide\Forum-Settings.md
    - Knowledge Base Settings: Administration-Guide\Knowledge-Base-Settings.md
    - Help Desk Settings: Administration-Guide\Help-Desk-Settings.md
    - Workflows: Administration-Guide\Workflows.md
    - Event Notifications: Administration-Guide\Event-Notifications.md
    - Appendices:
      - Troubleshooting: Administration-Guide\Appendix-A----Troubleshooting.md
      - Using with SSL: Administration-Guide\Appendix-B----Using-with-SSL.md
      - Sending Email through IIS: Administration-Guide\Appendix-C----Sending-Email-through-IIS.md
      - Upgrading: Administration-Guide\Appendix-D----Upgrading.md
  - Integrations: 
    - Email:
      - Installing: Email-Integration-Guide\Installing-the-Email-Integration-Service.md
      - Configuring: Email-Integration-Guide\Configuring-the-Email-Integration-Service.md
      - Using: Email-Integration-Guide\Using-the-Email-Integration-Service-with-KronoDesk.md
    - Migration: 
      - Importing from Excel: Migration-and-Integration-Guide\Importing-from-Microsoft-Excel.md