site_name: KronoDocs

repo_name: Inflectra
repo_url: https://www.inflectra.com
site_url: https://kronodoc.inflectra.com/

theme: 
  name: mkdocs
  custom_dir: inflectra_mkdocs
nav:
  - User Manual:
    - Functionality Overview: User_Manual\Functionality Overview.md
    - Home Page: User_Manual\Home Page.md
    - Knowledge Base: User_Manual\Knowledge Base.md
    - Forums: User_Manual\Forums.md
    - Help Desk: User_Manual\Help Desk.md
    - User Profile: User_Manual\User Profile.md
    - Reports: User_Manual\Reports.md
  - Quick Start Guide:
    - Getting Started: Quick_Start_Guide\Getting Started.md
    - Using the Help Desk Ticketing System: Quick_Start_Guide\Using the Help Desk Ticketing System.md
    - Configuring and Customizing: Quick_Start_Guide\Configuring and Customizing.md
    - Appendix A-Sample Users: Quick_Start_Guide\Appendix A- Sample Users.md
  - Integrations: 
    - Email:
      - Installing: Email_Integration_Guide\Installing the Email Integration Service.md
      - Configuring: Email_Integration_Guide\Configuring the Email Integration Service.md
      - Using: Email_Integration_Guide\Using the Email Integration Service with KronoDesk.md
    - Migration: 
      - Importing from Excel: Migration_and_Integration_Guide\Importing from Microsoft Excel.md