site_name: KronoDocs

repo_name: Inflectra
repo_url: https://www.inflectra.com
site_url: https://kronodoc.inflectra.com/

theme: 
  name: mkdocs
  custom_dir: inflectra_mkdocs
nav:
  - User Manual:
    - Functionality Overview: User_Manual\Functionality Overview.md
    - Home Page: User_Manual\Home Page.md
    - Knowledge Base: User_Manual\Knowledge Base.md
    - Forums: User_Manual\Forums.md
    - Help Desk: User_Manual\Help Desk.md
    - User Profile: User_Manual\User Profile.md
    - Reports: User_Manual\Reports.md
  - Quick Start Guide:
    - Getting Started: Quick_Start_Guide\Getting Started.md
    - Using the Help Desk Ticketing System: Quick_Start_Guide\Using the Help Desk Ticketing System.md
    - Configuring and Customizing: Quick_Start_Guide\Configuring and Customizing.md
    - Appendix A-Sample Users: Quick_Start_Guide\Appendix A- Sample Users.md
  - Administration Guide: 
    - Installing KronoDesk: Administration_Guide\Installing KronoDesk.md
    - System Administration: Administration_Guide\System Administration.md
    - System Settings: Administration_Guide\System Settings.md
    - Users: Administration_Guide\Users.md
    - Forum Settings: Administration_Guide\Forum Settings.md
    - Knowledge Base Settings: Administration_Guide\Knowledge Base Settings.md
    - Help Desk Settings: Administration_Guide\Help Desk Settings.md
    - Workflows: Administration_Guide\Workflows.md
    - Event Notifications: Administration_Guide\Event Notifications.md
    - Appendices:
      - Troubleshooting: Administration_Guide\Appendix A -- Troubleshooting.md
      - Using with SSL: Administration_Guide\Appendix B -- Using with SSL.md
      - Sending Email through IIS: Administration_Guide\Appendix C -- Sending Email through IIS.md
      - Upgrading: Administration_Guide\Appendix D -- Upgrading.md
  - Integrations: 
    - Email:
      - Installing: Email_Integration_Guide\Installing the Email Integration Service.md
      - Configuring: Email_Integration_Guide\Configuring the Email Integration Service.md
      - Using: Email_Integration_Guide\Using the Email Integration Service with KronoDesk.md
    - Migration: 
      - Importing from Excel: Migration_and_Integration_Guide\Importing from Microsoft Excel.md